function phpConfig () {
  sudo apt-get update
  sudo apt-get -y install lsb-release ca-certificates curl apt-transport-https
  sudo curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
  sudo dpkg -i /tmp/debsuryorg-archive-keyring.deb
  sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
  sudo apt-get update
}

function php () {
  phpConfig
  sudo apt update

  sudo apt install -y \
    libapache2-mod-php8.4 \
    libapache2-mod-php8.4-dbgsym \
    libphp8.4-embed \
    libphp8.4-embed-dbgsym \
    php8.4 \
    php8.4-amqp \
    php8.4-amqp-dbgsym \
    php8.4-apcu \
    php8.4-apcu-dbgsym \
    php8.4-ast \
    php8.4-ast-dbgsym \
    php8.4-bcmath \
    php8.4-bcmath-dbgsym \
    php8.4-bz2 \
    php8.4-bz2-dbgsym \
    php8.4-cgi \
    php8.4-cgi-dbgsym \
    php8.4-cli \
    php8.4-cli-dbgsym \
    php8.4-common \
    php8.4-common-dbgsym \
    php8.4-curl \
    php8.4-curl-dbgsym \
    php8.4-dba \
    php8.4-dba-dbgsym \
    php8.4-decimal \
    php8.4-decimal-dbgsym \
    php8.4-dev \
    php8.4-dio \
    php8.4-dio-dbgsym \
    php8.4-ds \
    php8.4-ds-dbgsym \
    php8.4-enchant \
    php8.4-enchant-dbgsym \
    php8.4-excimer \
    php8.4-excimer-dbgsym \
    php8.4-fpm \
    php8.4-fpm-dbgsym \
    php8.4-gd \
    php8.4-gd-dbgsym \
    php8.4-gearman \
    php8.4-gearman-dbgsym \
    php8.4-gmp \
    php8.4-gmp-dbgsym \
    php8.4-gnupg \
    php8.4-gnupg-dbgsym \
    php8.4-grpc \
    php8.4-grpc-dbgsym \
    php8.4-http \
    php8.4-http-dbgsym \
    php8.4-igbinary \
    php8.4-igbinary-dbgsym \
    php8.4-imagick \
    php8.4-imagick-dbgsym \
    php8.4-imap \
    php8.4-imap-dbgsym \
    php8.4-inotify \
    php8.4-inotify-dbgsym \
    php8.4-interbase \
    php8.4-interbase-dbgsym \
    php8.4-intl \
    php8.4-intl-dbgsym \
    php8.4-ldap \
    php8.4-ldap-dbgsym \
    php8.4-lz4 \
    php8.4-lz4-dbgsym \
    php8.4-mailparse \
    php8.4-mailparse-dbgsym \
    php8.4-maxminddb \
    php8.4-maxminddb-dbgsym \
    php8.4-mbstring \
    php8.4-mbstring-dbgsym \
    php8.4-mcrypt \
    php8.4-mcrypt-dbgsym \
    php8.4-memcache \
    php8.4-memcache-dbgsym \
    php8.4-memcached \
    php8.4-memcached-dbgsym \
    php8.4-mongodb \
    php8.4-mongodb-dbgsym \
    php8.4-msgpack \
    php8.4-msgpack-dbgsym \
    php8.4-mysql \
    php8.4-mysql-dbgsym \
    php8.4-oauth \
    php8.4-oauth-dbgsym \
    php8.4-odbc \
    php8.4-odbc-dbgsym \
    php8.4-opcache \
    php8.4-opcache-dbgsym \
    php8.4-opentelemetry \
    php8.4-opentelemetry-dbgsym \
    php8.4-pcov \
    php8.4-pcov-dbgsym \
    php8.4-pgsql \
    php8.4-pgsql-dbgsym \
    php8.4-phalcon \
    php8.4-phalcon-dbgsym \
    php8.4-phpdbg \
    php8.4-phpdbg-dbgsym \
    php8.4-pq \
    php8.4-pq-dbgsym \
    php8.4-protobuf \
    php8.4-protobuf-dbgsym \
    php8.4-ps \
    php8.4-ps-dbgsym \
    php8.4-pspell \
    php8.4-pspell-dbgsym \
    php8.4-psr \
    php8.4-psr-dbgsym \
    php8.4-raphf \
    php8.4-raphf-dbgsym \
    php8.4-rdkafka \
    php8.4-rdkafka-dbgsym \
    php8.4-readline \
    php8.4-readline-dbgsym \
    php8.4-redis \
    php8.4-redis-dbgsym \
    php8.4-rrd \
    php8.4-rrd-dbgsym \
    php8.4-smbclient \
    php8.4-smbclient-dbgsym \
    php8.4-snmp \
    php8.4-snmp-dbgsym \
    php8.4-soap \
    php8.4-soap-dbgsym \
    php8.4-solr \
    php8.4-solr-dbgsym \
    php8.4-sqlite3 \
    php8.4-sqlite3-dbgsym \
    php8.4-ssh2 \
    php8.4-ssh2-dbgsym \
    php8.4-stomp \
    php8.4-stomp-dbgsym \
    php8.4-swoole \
    php8.4-swoole-dbgsym \
    php8.4-sybase \
    php8.4-sybase-dbgsym \
    php8.4-tidy \
    php8.4-tidy-dbgsym \
    php8.4-uopz \
    php8.4-uopz-dbgsym \
    php8.4-uploadprogress \
    php8.4-uploadprogress-dbgsym \
    php8.4-uuid \
    php8.4-uuid-dbgsym \
    php8.4-vips \
    php8.4-vips-dbgsym \
    php8.4-xdebug \
    php8.4-xhprof \
    php8.4-xhprof-dbgsym \
    php8.4-xlswriter \
    php8.4-xlswriter-dbgsym \
    php8.4-xml \
    php8.4-xml-dbgsym \
    php8.4-xmlrpc \
    php8.4-xmlrpc-dbgsym \
    php8.4-xsl \
    php8.4-yaml \
    php8.4-yaml-dbgsym \
    php8.4-zip \
    php8.4-zip-dbgsym \
    php8.4-zmq \
    php8.4-zmq-dbgsym \
    php8.4-zstd \
    php8.4-zstd-dbgsym
}
